import "./globals.css";

export const metadata = {
  title: "Paramotor",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className=" mx-56">
        {children}
        </div>
      </body>
    </html>
  );
}
